# Generated by Django 4.0.3 on 2022-04-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
