# Generated by Django 4.0.3 on 2022-04-04 07:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Age', models.PositiveIntegerField()),
                ('Contact_number', models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('Picture', models.ImageField(upload_to='Health_services-Doctors_profile_images')),
                ('Still_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
                ('Is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health_center_contactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Contact_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('Email_address', models.EmailField(max_length=254)),
                ('Available_days', models.CharField(max_length=20)),
                ('Open_time', models.TimeField()),
                ('Close_time', models.TimeField()),
                ('Open_today', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
                ('Fees', models.PositiveBigIntegerField()),
                ('Is_available', models.BooleanField(default=True)),
                ('Need_appointment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seasonal_health_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Goal', models.TextField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Open_time', models.TimeField()),
                ('Close_time', models.TimeField()),
                ('Location', models.CharField(max_length=60)),
                ('Available_today', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Assigned_doctor', models.ManyToManyField(to='Health_services.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Supported_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalServices_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beneficiary_name', models.CharField(max_length=40)),
                ('Appointment_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Is_valid', models.BooleanField(default=False)),
                ('Is_expired', models.BooleanField(default=False)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SSname', to=settings.AUTH_USER_MODEL)),
                ('Service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_type', to='Health_services.seasonal_health_service')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beneficiary_name', models.CharField(max_length=30)),
                ('Appointment_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Labtestrequest_name', to=settings.AUTH_USER_MODEL)),
                ('Requested_labTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requested_labTest', to='Health_services.laboratory_test')),
            ],
        ),
        migrations.CreateModel(
            name='Donation_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_name', models.CharField(max_length=50)),
                ('Account_number', models.CharField(max_length=50)),
                ('Is_visible', models.BooleanField(default=True)),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health_services.supported_bank')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Awarded_date', models.DateField()),
                ('Certificate_image', models.ImageField(upload_to='Health_services-Doctors_certificates')),
                ('Is_visible', models.BooleanField(default=True)),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health_services.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health_services.doctors_specialty'),
        ),
        migrations.CreateModel(
            name='Check_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Is_available', models.BooleanField(default=True)),
                ('Assigned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health_services.doctor')),
            ],
        ),
    ]
