# Generated by Django 4.0.3 on 2022-04-06 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0002_alter_doctor_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contact_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
