# Generated by Django 4.0.3 on 2022-04-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0003_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonal_health_service',
            name='Is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
