# Generated by Django 4.0.3 on 2022-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0004_seasonal_health_service_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonal_health_service',
            name='Image',
            field=models.ImageField(default='SS.png', upload_to='Health_services-Seasonal_services'),
        ),
    ]
