# Generated by Django 4.0.3 on 2022-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0005_seasonal_health_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_info',
            name='Bank_image',
            field=models.ImageField(default='Gcash.png', upload_to='Health_services_Bank-images'),
        ),
        migrations.AlterField(
            model_name='donation_info',
            name='Bank',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Supported_bank',
        ),
    ]
