# Generated by Django 4.0.3 on 2022-04-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0007_alter_doctor_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_info',
            name='Bank_image',
            field=models.ImageField(default='Banking.jpg', upload_to='Health_services_Bank-images'),
        ),
    ]
