# Generated by Django 4.0.3 on 2022-04-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0008_alter_donation_info_bank_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_info',
            name='Is_visible',
        ),
    ]
