# Generated by Django 4.0.3 on 2022-04-12 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Health_services', '0010_health_service_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_service_recipients',
            name='User_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
