# Generated by Django 4.0.3 on 2022-04-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0012_health_service_recipients_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalservices_request',
            name='Is_expired',
        ),
        migrations.RemoveField(
            model_name='seasonalservices_request',
            name='Is_valid',
        ),
    ]
