# Generated by Django 4.0.3 on 2022-04-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_services', '0013_remove_seasonalservices_request_is_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonal_health_service',
            name='Available_today',
        ),
    ]
