# Generated by Django 4.0.3 on 2022-03-20 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supersystem_webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_details',
            name='Contact_number',
            field=models.CharField(default=639123456789, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
