# Generated by Django 4.0.3 on 2022-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supersystem_webpages', '0003_brgy_photos_list_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='brgy_photos',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
