# Generated by Django 4.0.3 on 2022-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supersystem_webpages', '0004_brgy_photos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brgy_photos',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
