# Generated by Django 4.0.3 on 2022-03-20 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supersystem_webpages', '0005_alter_brgy_photos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='Age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='Contact_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
