# Generated by Django 4.0.3 on 2022-03-20 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supersystem_webpages', '0006_alter_account_details_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='Age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='Contact_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
